apply plugin: 'com.android.application'

android {
    namespace 'it.paolo.allenamentoportieri'
    compileSdk 35

    defaultConfig {
        applicationId 'it.paolo.allenamentoportieri'
        minSdk 24
        targetSdk 35
        versionCode 8
        versionName '1.7'
        manifestPlaceholders = [appLabel: 'Allenamento Portieri']
    }

    buildTypes {
        debug {
            applicationIdSuffix '.test'
            versionNameSuffix '-test'
            manifestPlaceholders = [appLabel: 'Allenamento Portieri TEST']
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
